version: "3.8"

include:
  - supabase/docker/docker-compose.yml

services:
  superflows:
    build:
      context: ../../
      dockerfile: ./docker/development/Dockerfile
    container_name: superflows
    depends_on:
      - kong # defined by another_domain
    ports:
      - ${SUPERFLOWS_PORT}:3000
    env_file:
      - .env
    volumes:
      - ../../:/app
      - /app/node_modules


networks:
  superflows:
   