version: "3.8"

include:
  - supabase/docker/docker-compose.yml

services:
  superflows:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./docker/development/Dockerfile
    container_name: superflows
    command:
      [
        "sh",
        "-c",
        "echo 'y' | npx supabase db push --db-url='postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}' && npm run dev",
      ]
    depends_on:
      - kong # defined by another_domain
    ports:
      - ${SUPERFLOWS_PORT}:3000
    env_file:
      - .env
    volumes:
      - ../../:/app
      - /app/node_modules

networks:
  superflows:
