version: "3.8"

include:
  - supabase/docker/docker-compose.yml

services:
  superflows:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    depends_on:
      - kong # defined by another_domain
    