create table "public"."usage" (
    "org_id" bigint generated by default as identity not null,
    "date" date,
    "usage" double precision
);


alter table "public"."usage" enable row level security;

CREATE UNIQUE INDEX usage_pkey ON public.usage USING btree (org_id);

alter table "public"."usage" add constraint "usage_pkey" PRIMARY KEY using index "usage_pkey";

alter table "public"."usage" add constraint "usage_org_id_fkey" FOREIGN KEY (org_id) REFERENCES organizations(id) not valid;

alter table "public"."usage" validate constraint "usage_org_id_fkey";

create policy "enable all based on organisation id"
on "public"."usage"
as permissive
for all
to public
using ((auth.uid() IN ( SELECT profiles.id
   FROM profiles
  WHERE (profiles.org_id = usage.org_id))));




