import { Action } from "../lib/types";

export const testActions: Action[] = [
  {
    tag: 1,
    action_type: "http",
    description: "",
    active: true,
    created_at: "2022-01-01T00:00:00Z",
    id: 1,
    keys_to_keep: null,
    name: "action_a",
    org_id: 1,
    parameters: null,
    path: "/api/v1/endpoint1",
    request_body_contents: null,
    request_method: "POST",
    responses: null,
    api_id: "12345",
    requires_confirmation: false,
    link_url: "",
    link_name: "",
  },
  {
    tag: 1,
    action_type: "http",
    description: "",
    active: true,
    created_at: "2022-01-01T00:00:00Z",
    id: 2,
    keys_to_keep: null,
    name: "action_b",
    org_id: 1,
    parameters: null,
    path: "/api/v2/endpoint2",
    request_body_contents: null,
    request_method: "GET",
    responses: null,
    api_id: "12345",
    requires_confirmation: false,
    link_url: "",
    link_name: "",
  },
  {
    tag: 1,
    action_type: "http",
    description: "",
    active: true,
    created_at: "2022-01-01T00:00:00Z",
    id: 3,
    keys_to_keep: null,
    name: "action_c",
    org_id: 1,
    parameters: null,
    path: "/api/v2/endpoint3",
    request_body_contents: null,
    request_method: "PUT",
    responses: null,
    api_id: "12345",
    requires_confirmation: false,
    link_url: "",
    link_name: "",
  },
  {
    tag: 1,
    action_type: "http",
    description: "",
    active: true,
    created_at: "2022-01-01T00:00:00Z",
    id: 3,
    keys_to_keep: null,
    name: "action_d",
    org_id: 1,
    parameters: null,
    path: "/api/v2/endpoint3/{id}",
    request_body_contents: null,
    request_method: "PUT",
    responses: null,
    api_id: "12345",
    requires_confirmation: false,
    link_url: "",
    link_name: "",
  },
  {
    tag: 1,
    action_type: "http",
    description: "",
    active: true,
    created_at: "2022-01-01T00:00:00Z",
    id: 3,
    keys_to_keep: null,
    name: "action_e",
    org_id: 1,
    parameters: null,
    path: "/api/v2/{id}/endpoint3",
    request_body_contents: null,
    request_method: "PUT",
    responses: null,
    api_id: "12345",
    requires_confirmation: false,
    link_url: "",
    link_name: "",
  },
  {
    tag: 1,
    action_type: "http",
    description: "",
    active: true,
    created_at: "2022-01-01T00:00:00Z",
    id: 3,
    keys_to_keep: null,
    name: "action_f",
    org_id: 1,
    parameters: null,
    path: "/api/0/teams/{organization_slug}/{team_slug}/",
    request_body_contents: null,
    request_method: "PUT",
    responses: null,
    api_id: "12345",
    requires_confirmation: false,
    link_url: "",
    link_name: "",
  },
];
